language: python
python:
  - 2.7
  - 3.4
# Django Versions
env:
  - DJANGO_VERSION=1.7.1
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.6
# command to install dependencies
install:
  - pip install Django==$DJANGO_VERSION
  - if [[ $TRAVIS_PYTHON_VERISON == 2.7 ]]; then pip install -r requirements_2_7.txt; fi
# command to run tests
script: python manage.py test -v 3
